/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

/**
 * Case 4
 */
export class ArrayOfCatOrDogObjects extends SpeakeasyBase {
    @SpeakeasyMetadata()
    value: any[];
}
