/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

export class Cat extends SpeakeasyBase {
    @SpeakeasyMetadata()
    meows: boolean;
}
