/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

/**
 * Case 1
 */
export class CatOrDog extends SpeakeasyBase {
    @SpeakeasyMetadata()
    value: any;
}
