/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";

/**
 * Case 3
 */
export class CatsOrADogOrWolves extends SpeakeasyBase {
    @SpeakeasyMetadata()
    value: any;
}
