/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Cat } from "./cat";

/**
 * Case 2
 */
export class CatsOrDogs extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: Cat })
    value: Cat[];
}
